name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy to GitHub Pages
        env: 
          GITHUB_TOKEN: ${{ secrets.JEKYLL_PAT }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        uses: BryanSchuetz/jekyll-deploy-gh-pages@master 



# source https://jekyllrb.com/docs/continuous-integration/github-actions/
# https://github.com/marketplace/actions/jekyll-deploy-gh-pages#example
# https://github.com/BryanSchuetz/jekyll-deploy-gh-pages
